AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: "String"
  LambdaCode:
    Type: "String"
    Default: "aws-sagemaker-ilpd-app.jar"
  SageMakerEndpoint:
    Type: "String"

Resources:
  LambdaFunctionHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Lambda handler that calls SageMaker for liver disease prediction
      Timeout: 30
      MemorySize: 512
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref LambdaCode
      Runtime: java8
      Handler: com.amazonaws.samples.liver_disease.LambdaFunctionHandler
      Environment:
        Variables:
          SAGEMAKER_ENDPOINT: !Ref SageMakerEndpoint

      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement: #- Allow access to SageMaker
            - Effect: Allow
              Action:
                - sagemaker:*
              Resource: "*"

      # Event sources to attach to this function. In this case, we are attaching
      # one API Gateway endpoint to the Lambda function. The function is
      # called when an HTTP request is made to the API Gateway endpoint.
      Events:
        LiverDiseaseApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /predict-liver-disease
            Method: POST

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Variables:
        LambdaFunctionName: !Ref LambdaFunctionHandler

Outputs:
  ProdDataEndpoint:
    Description: "API Prod stage endpoint"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict-liver-disease"